codecov:
  branch: main
  notify:
    require_ci_to_pass: no

coverage:
  range: 70..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 5%
        only_pulls: true

    patch:
      default:
        target: auto
        threshold: 5%
        only_pulls: true

    changes: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "**/build/**/*"
  - "**/*.gradle"
  - "**/*.json"
  - "**/*.xml"

comment:
  layout: "header, diff, flags"
  behavior: default
  require_changes: false
