name: Android 🤖

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set up JDK
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: 'temurin'
          java-version: '19'
          cache: 'gradle'
      - name: Decrypt google-services.json
        run: |
          ./scripts/decrypt.sh android/google-services.json.gpg android/google-services.json ${{ secrets.FIREBASE_GPG }}
      - name: Linting
        run: make lint-android

  test:
    name: Test & Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set up JDK
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: 'temurin'
          java-version: '19'
          cache: 'gradle'
      - name: Decrypt google-services.json
        run: |
          ./scripts/decrypt.sh android/google-services.json.gpg android/google-services.json ${{ secrets.FIREBASE_GPG }}
      - name: Test
        run: make report-android
      - name: Report
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: ./build/reports/kover/report.xml
          flags: android
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEY_STORE_GPG: ${{ secrets.KEY_STORE_GPG }}
      FIREBASE_GPG: ${{ secrets.FIREBASE_GPG }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      PRIVACY_POLICY_URL: ${{ vars.PRIVACY_POLICY_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set up JDK
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: 'temurin'
          java-version: '19'
          cache: 'gradle'
      - name: Decrypt Keystore
        run: |
          ./scripts/decrypt.sh keystore/drappula.jks.gpg keystore/drappula.jks ${{ secrets.KEY_STORE_GPG }}
      - name: Decrypt google-services.json
        run: |
          ./scripts/decrypt.sh android/google-services.json.gpg android/google-services.json ${{ secrets.FIREBASE_GPG }}
      - name: Assemble
        run: make FLAVOR=Production BUILD_TYPE=Release assemble-android
      - name: Bundle
        run: make FLAVOR=Production BUILD_TYPE=Release bundle-android
